services:
  - type: web
    name: zen-finance
    runtime: python
    rootDir: finance_web_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
