services:
  - type: web
    name: feedme-meal-planner
    runtime: python
    rootDir: harvard_meal_planner_website
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
