import { addDays, toISODate } from './utils/dates.js';

/** Gallery / “View Demo” seed — dates are relative to “today”. */
export function buildDemoState() {
  const today = toISODate();
  const y = (d) => {
    const x = new Date();
    x.setDate(x.getDate() - d);
    return x.toISOString().slice(0, 10);
  };
  const range = (from, to) => {
    const out = [];
    for (let d = from; d <= to; d++) out.push(y(d));
    return out;
  };

  const demo = {
    profile: {
      name: 'Elena',
      email: 'elena@demo.quirkly',
      onboardingCompleted: true,
      motivationLevel: 7,
      focusStyle: 'deep_work',
      forgetfulnessLevel: 'low',
      routinePreference: 'structure',
      taskInitiationDifficulty: 'medium',
      prefersSimpleView: false,
      encouragementPreference: 'minimal',
      quizAnswers: {
        improvementAreas: ['Mental Wellness', 'Studying', 'Fitness'],
        whyHabits: 'Stay focused without burning out.',
        sleepNote: 'Aim for 11pm wind-down',
        motivationSlider: 7,
        idealDay: 'Deep morning work, light evening reset.',
        overwhelm: 'Big ambiguous projects',
        procrastinationReason: 'Distraction',
        pastBarriers: ['Life got too busy'],
        confidenceTopics: 'Context switching',
        scheduleOutline: 'Classes then project blocks',
        routineStyle: 'structure',
        energyPeak: 'morning',
        accountability: 'gentle',
        initialHabitIdeas: ['Deep Hydration', 'Morning Journal', 'Deep Work Block'],
        dailyTimeCommitmentMinutes: 45,
        initialHabitCount: 5,
      },
      derivedProfileType: 'The Deep Diver',
      derivedProfileBlurb:
        'You protect focus with systems—and feel the cost of context-switching. Shorter starter steps and one-habit mode help.',
      derivedChallenges: [
        'Distractions and forgotten cues can break your rhythm mid-day.',
        'Ambiguous projects stall without a clear first move.',
      ],
      derivedStrengths: [
        'You respond well to clear structure and visible streaks.',
        'Motivation is already on your side—channel it into small repeats.',
      ],
      memberSince: 'Oct 2025',
      focusScore: 85,
    },
    habits: [
      {
        id: 'demo-1',
        title: 'Deep Hydration',
        description: 'Drink 500ml water with lemon before coffee.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Wellness',
        preferredTime: 'morning',
        createdAt: y(40),
        completedDates: [...range(0, 15), y(18), y(20), y(22)],
        active: true,
        suggestedMicroStep: 'Fill one glass and place it on your desk.',
        progressTarget: 8,
        progressCurrent: 7,
        subtasks: ['Morning glass', 'Pre-lunch', 'Afternoon'],
      },
      {
        id: 'demo-2',
        title: 'Morning Journal',
        description: 'Three gratitudes and one focus for today.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Mental Wellness',
        preferredTime: 'morning',
        createdAt: y(28),
        completedDates: [...range(0, 4), y(7), y(8), y(12)],
        active: true,
        suggestedMicroStep: 'Write one line you are grateful for.',
        progressTarget: 10,
        progressCurrent: 5,
      },
      {
        id: 'demo-3',
        title: 'Box Breathing',
        description: '5 minutes of square breathing.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Mental Wellness',
        preferredTime: 'afternoon',
        createdAt: y(21),
        completedDates: [...range(1, 6), y(9), y(11)],
        active: true,
        suggestedMicroStep: 'One slow 4-4-4-4 cycle.',
        progressTarget: 5,
        progressCurrent: 2,
      },
      {
        id: 'demo-4',
        title: 'Inbox Zero Sweep',
        description: 'Clear or triage email for 10 minutes.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Career',
        preferredTime: 'afternoon',
        createdAt: y(1),
        completedDates: [],
        active: true,
        suggestedMicroStep: 'Archive or reply to one message.',
        progressTarget: 5,
        progressCurrent: 0,
      },
      {
        id: 'demo-5',
        title: 'Evening Stretch',
        description: 'Five minutes of hip and shoulder mobility.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Fitness',
        preferredTime: 'evening',
        createdAt: y(3),
        completedDates: [y(1)],
        active: true,
        suggestedMicroStep: 'Set a 5-minute timer and start standing.',
        progressTarget: 7,
        progressCurrent: 1,
      },
      {
        id: 'demo-6',
        title: 'No-Phone Walk',
        description: 'A short walk without headphones or phone.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Fitness',
        preferredTime: 'evening',
        createdAt: y(30),
        completedDates: [y(4), y(8), y(9), y(15), y(21), y(22), y(28)],
        active: true,
        suggestedMicroStep: 'Step outside for two quiet minutes.',
      },
      {
        id: 'demo-7',
        title: 'Long Study Block',
        description: '90 minutes of deep studying, twice a week.',
        frequency: 'weekly',
        targetDays: 2,
        category: 'Studying',
        preferredTime: 'morning',
        createdAt: y(35),
        completedDates: [y(0), y(2), y(7), y(9), y(14), y(16), y(21), y(23)],
        active: true,
        suggestedMicroStep: 'Open notes and write the next heading.',
        progressTarget: 2,
        progressCurrent: 2,
        subtasks: ['Clear desk', 'Timer on', 'One paragraph summary'],
      },
      {
        id: 'demo-8',
        title: 'Strength Circuit',
        description: 'Bodyweight circuit three times a week.',
        frequency: 'weekly',
        targetDays: 3,
        category: 'Fitness',
        preferredTime: 'afternoon',
        createdAt: y(25),
        completedDates: [y(3), y(10), y(11), y(17), y(18), y(19)],
        active: true,
        suggestedMicroStep: 'Do one set of squats.',
        progressTarget: 3,
        progressCurrent: 1,
      },
      {
        id: 'demo-9',
        title: 'Reading Sprint',
        description: 'Read 10 pages of nonfiction.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Studying',
        preferredTime: 'evening',
        createdAt: y(18),
        completedDates: [...range(2, 8), y(12)],
        active: true,
        suggestedMicroStep: 'Open the book to the bookmark.',
        snoozeUntil: addDays(today, 1),
        progressTarget: 10,
        progressCurrent: 4,
      },
      {
        id: 'demo-10',
        title: 'Deep Work Block',
        description: 'One protected 45-minute focus session.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Career',
        preferredTime: 'morning',
        createdAt: y(14),
        completedDates: [...range(0, 2), y(5), y(6)],
        active: true,
        suggestedMicroStep: 'Silence notifications for 45 minutes.',
        progressTarget: 5,
        progressCurrent: 3,
        subtasks: ['Define the one outcome', 'Start timer', 'Log what shipped'],
      },
      {
        id: 'demo-11',
        title: 'Language Flashcards',
        description: 'Review 15 cards in your deck.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Studying',
        preferredTime: 'evening',
        createdAt: y(45),
        completedDates: [y(12), y(25), y(33), y(40)],
        active: true,
        suggestedMicroStep: 'Open the app and do five cards.',
        progressTarget: 15,
        progressCurrent: 2,
      },
      {
        id: 'demo-12',
        title: 'Cold Shower Challenge',
        description: 'Paused after two weeks — kept for export history.',
        frequency: 'daily',
        targetDays: 1,
        category: 'Wellness',
        preferredTime: 'morning',
        createdAt: y(50),
        completedDates: range(30, 44),
        active: false,
        suggestedMicroStep: 'End shower with 20 cold seconds.',
        progressTarget: 14,
        progressCurrent: 14,
      },
    ],
    theme: 'ink',
    morningNudges: true,
    weeklyReports: true,
  };

  demo.habits = demo.habits.map((h) => ({
    ...h,
    completedDates: (h.completedDates || []).filter((d) => d <= today),
  }));

  return demo;
}

/** True when the GitHub Pages gallery build sets VITE_DEMO=true */
export const isDemo = import.meta.env.VITE_DEMO === 'true';
